[package]
name = "advent_of_rust"
version = "0.1.0"
authors = ["Frank van der Stam <frank_stam5@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
permutohedron = "0.2.4"
ggez = "0.5"
